### PR TITLE
Support unified (per user) experiment results file

### PR DESCRIPTION
**Pull request by bboudaoud-nv**
Support a unified user/experiment results database for cleaner output.

### CODE REVIEW

**Comment by bboudaoud-nv** [comment]
This branch doesn't (currently) have support for experiments that use different `sessParamsToLog` between sessions. This could potentially be supported using some clever logic in the future.

**Comment by jspjutNV** [comment]
I think the default should be to log to a single file by default (once we get this working as intended).

We also should think through the "single log file" design in case someone is working on multiple revisions of the same experiment. We may want something to uniquify the file based on an particular experiment. Maybe we could append a hash of the `experimentconfig.Any`.

**Comment by jspjutNV** [comment]
We also should think through the "single log file" design in case someone is working on multiple revisions of the same experiment. We may want something to uniquify the file based on an particular experiment. Maybe we could append a hash of the `experimentconfig.Any`.

**Comment by bboudaoud-nv** [comment]
A hash (of a reformatted experiment config, that ignores whitespace/invalid parameters) has been added to the filename here. If @joohwankimNV agrees that a unified experiment db then we can make this change and merge this PR.

**Review by jspjutNV — APPROVED** [review]

**Pull request merged**
