### PR TITLE
Scene configuration

### LINKED ISSUE #174: FPSci-specific scene configuration
Currently FPSci `scene.any` files require additional fields not found in "default" G3D scenes. These include:
* The `Physics` descriptor field (borrowed from the `simpleGame` sample's `PhysicsScene` implementation
* The `player` descriptor field (used to set spawn location/heading for our `PlayerEntity` class)
* A `playerCamera` camera descriptor field, used to defined the camera that is (implicitly) linked to the `playerEntity`

Additionally, current/future feature requests tend towards further increasing information that might be useful to store in the `scene.any` file including: 
* Issue #133 has a request for adding named spawn locations to the scene file
* The possibility of storing (named) world-space targets within a scene file (then optionally referencing them from an experiment config) so that the target motion is consistent with scene geometry

In an effort to allow maximum flexibility of the application and re-use G3D's existing `scene.any` files it makes sense to consider a way to load/reuse default G3D scenes, but also customize them without a need to edit the original scene files. Perhaps we should consider an `fpsci.scene.any` file format affiliated with the G3D `scene.any` file explicitly/by name that would allow us to add this data to the scene without a need for modifying/appending to the scene file.

### PR DESCRIPTION
**Pull request by bboudaoud-nv**
This branch adds functionality for a `scene` parameter within the general configuration structure (and a corresponding `SceneConfig` class within our configuration heirarchy). This allows the user to take "clean"/unmodified G3D scene files and add FPSci-specific configuration to them in an experiment config file (rather than in the scene file itself).

New `.fpsci.scene.Any` files can be created and included as the scene using `scene = #include("myfile.fpsci.scene.Any")` at an experiment/session level.

Merging this PR closes #174.

### CODE REVIEW

**Comment by jspjutNV** [comment]
Looking at this pull request, I believe some documentation updates will be needed to reflect this change.

**Comment by bboudaoud-nv** [comment]
Currently the `SceneConfig` supports:
* Scene name (same as historically)
* Player camera name override (defaults to the scene's `defaultCamera`)
* Reset height override (defaults to the scene's `Physics` field's `minHeight` parameter if specified)
* Spawn position/heading override (defaults to the scene's `PlayerEntity` settings if specified)

If there are additional fields we'd like to support (i.e. `MarkerEntity` based spawn locations) we can add these as well, but we'll need a full description of how this functionality is intended to work within the application.

**Comment by bboudaoud-nv** [comment]
I'm going to open this PR for review. If there are any additional requests for fields that should be specifiable in the Scene config we can add them in the PR during the review/as new issues.

**Comment by jspjutNV** [comment]
This pull request appears to break compatibility with previous experiment configs. @joohwankimNV , are you prepared to accept this change?

**Comment by jspjutNV** [comment]
> This pull request appears to break compatibility with previous experiment configs. @joohwankimNV , are you prepared to accept this change?

@joohwankimNV told me that this change is a welcome one. I'm working on testing this change an improving error messaging accordingly.

**Comment by jspjutNV** [comment]
Will this one also close #133 ?

**Comment by jspjutNV** [comment]
8 of the tests currently fail. I'll need to investigate this failure, and likely the test configs will need to be updated to work correctly.

**Comment by jspjutNV** [comment]
Good news, after merging in master the target sizes test also passes, so we have 5 passing and the same 8 failing.

**Comment by jspjutNV** [comment]
So far everything I've tried to do that appears to match the documentation has caused the tests to crash. I'm not sure what I'm doing wrong. I've tried:

```
    scene = {
        name = "G3D Simple Cornell Box (Empty CO)";
    }
```
and a few similar variants.

**Comment by jspjutNV** [comment]
I've discovered what I believe to be a bug due to `FPSci::updatePlayer()` and `FPSci::updateFromSceneConfig(player)` having overlapping functionality. A fix is in progress.

**Comment by jspjutNV** [comment]
I believe this one is finally ready to merge. I improved the documentation, merged a couple functions that were fighting, and made the player spawn at the specified location on start of each session as well as at first launch. All tests are passing as well with the updated scene in the experiment config.

**Pull request merged**
